# Este arquivo contém valores customizados para o Helm chart do kube-prometheus-stack.
# Vamos usá-lo para configurar o Prometheus para descobrir nossos microsserviços.

prometheus:
  prometheusSpec:
    # Adiciona uma configuração extra para o scrape (coleta de métricas)
    additionalScrapeConfigs:
      - job_name: 'kubernetes-services'
        kubernetes_sd_configs:
          - role: service
        relabel_configs:
          # Procura por services que tenham a anotação 'prometheus.io/scrape: true'
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          # Usa o nome do service como o nome do job
          - source_labels: [__meta_kubernetes_service_label_app]
            target_label: job
            replacement: $1
